# Generated by Django 4.2.4 on 2023-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='leval',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
