# Generated by Django 4.2.4 on 2023-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0003_course_leval'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_docx',
            field=models.FileField(null=True, upload_to='course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(null=True, upload_to='course_video'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(default='cover_default.jpg', upload_to='cover_pictures/'),
        ),
        migrations.AddField(
            model_name='course',
            name='durations',
            field=models.TimeField(default='01:00'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.IntegerField(default='0'),
        ),
    ]
