# Generated by Django 4.2.4 on 2023-08-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0005_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_docx',
            field=models.FileField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_default.jpg', upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pictures/'),
        ),
    ]
