# Generated by Django 4.2.4 on 2023-08-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0006_alter_course_course_docx_alter_course_course_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='durations',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
