# Generated by Django 4.2.4 on 2023-08-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0007_alter_course_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
