# Generated by Django 4.2.4 on 2023-08-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning_app', '0008_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
